server:
  port: 9005

spring:
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DiceGame?useSLL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
    username: root
    password: ma?in!123
